// Generated by CoffeeScript 1.5.0
(function() {
  var ComicMetaView, Page, Pages,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Page = (function(_super) {

    __extends(Page, _super);

    function Page() {
      this.onImageLoad = __bind(this.onImageLoad, this);
      this.fetch = __bind(this.fetch, this);
      Page.__super__.constructor.apply(this, arguments);
    }

    Page.prototype.fetch = function() {
      var preloader;
      preloader = new ImagePreloader({
        urls: [this.get('url')],
        complete: this.onImageLoad
      });
      return preloader.start();
    };

    Page.prototype.onImageLoad = function() {
      return this.set('fetched', true);
    };

    return Page;

  })(Backbone.Model);

  Pages = (function(_super) {

    __extends(Pages, _super);

    function Pages() {
      this.setCurrentPage = __bind(this.setCurrentPage, this);
      this.percentFetched = __bind(this.percentFetched, this);
      this.fetched = __bind(this.fetched, this);
      this.fetch = __bind(this.fetch, this);
      this.initialize = __bind(this.initialize, this);
      Pages.__super__.constructor.apply(this, arguments);
    }

    Pages.prototype.model = Page;

    Pages.prototype.initialize = function() {
      return this.currentPageIndex = 0;
    };

    Pages.prototype.fetch = function() {
      var _this = this;
      return _.map(this.models, function(model) {
        return model.fetch();
      });
    };

    Pages.prototype.fetched = function() {
      var _this = this;
      return _.filter(this.models, function(model) {
        return model.get('fetched');
      });
    };

    Pages.prototype.percentFetched = function() {
      return Math.round(this.fetched().length / this.size() * 100);
    };

    Pages.prototype.setCurrentPage = function(pageIndex) {
      if (!(pageIndex >= 0 && pageIndex < this.models.length)) {
        return;
      }
      this.currentPageIndex = pageIndex;
      return this.trigger('change:page', pageIndex);
    };

    return Pages;

  })(Backbone.Collection);

  ComicMetaView = (function(_super) {

    __extends(ComicMetaView, _super);

    function ComicMetaView() {
      this.render = __bind(this.render, this);
      this.initialize = __bind(this.initialize, this);
      ComicMetaView.__super__.constructor.apply(this, arguments);
    }

    ComicMetaView.prototype.initialize = function(options) {
      if (options == null) {
        options = {};
      }
      this.pages = options.pages;
      this.pages.on('change:fetched', this.render);
      return this.pages.on('change:page', this.render);
    };

    ComicMetaView.prototype.render = function() {
      return this.$el.html("<div class='page-index'>" + (this.pages.currentPageIndex + 1) + " of " + this.pages.length + "</div>\n<div class='progress'>Loaded " + (this.pages.percentFetched()) + "%</div>");
    };

    return ComicMetaView;

  })(Backbone.View);

  this.ComicReader = (function(_super) {

    __extends(ComicReader, _super);

    function ComicReader() {
      this.previousPage = __bind(this.previousPage, this);
      this.nextPage = __bind(this.nextPage, this);
      this.showPage = __bind(this.showPage, this);
      this.onKeyPress = __bind(this.onKeyPress, this);
      this.render = __bind(this.render, this);
      this.initialize = __bind(this.initialize, this);
      ComicReader.__super__.constructor.apply(this, arguments);
    }

    ComicReader.prototype.events = {
      'click .comic-image': 'nextPage'
    };

    ComicReader.prototype.initialize = function(options) {
      var _this = this;
      if (options == null) {
        options = {};
      }
      $(document).on("keyup", this.onKeyPress);
      this.pages = new Pages(_.map(options.urls || [], function(url) {
        return {
          url: url,
          fetched: false
        };
      }));
      this.pages.on('change:page', this.showPage);
      this.render();
      this.metaView = new ComicMetaView({
        el: ".comic-meta-wrap",
        pages: this.pages
      });
      this.pages.fetch();
      return this.pages.setCurrentPage(0);
    };

    ComicReader.prototype.render = function() {
      return this.$el.html(" <table class='comic-page-table' width=\"100%\" height=\"100%\" align=\"center\" valign=\"center\">\n  <tr>\n    <td class='comic-page-wrap'>\n      <div class='comic-meta-wrap'></div>\n      <div class='comic-image-wrap'></div>\n    </td>\n  </tr>\n</table>");
    };

    ComicReader.prototype.onKeyPress = function(e) {
      if (e.keyCode === 37) {
        return this.previousPage();
      } else if (e.keyCode === 39) {
        return this.nextPage();
      }
    };

    ComicReader.prototype.showPage = function(pageIndex) {
      var page;
      page = this.pages.at(pageIndex);
      this.$el.find(".comic-image-wrap").hide(0).html("<img class='comic-image' src='" + (page.get('url')) + "'>").fadeIn(50);
      return $(document).scrollTop(0);
    };

    ComicReader.prototype.nextPage = function() {
      return this.pages.setCurrentPage(this.pages.currentPageIndex + 1);
    };

    ComicReader.prototype.previousPage = function() {
      return this.pages.setCurrentPage(this.pages.currentPageIndex - 1);
    };

    return ComicReader;

  })(Backbone.View);

}).call(this);
